# docker-compose.yml
version: '3.8'

services:
  # 1. Infrastructure: Redis Cache Service (Uses Alpine - Minimal, No Git)
  redis:
    image: redis:7-alpine
    container_name: codespace_redis
    command: redis-server --appendonly yes
    ports: 
      - 6379:6379 
    volumes:
      - redis_data:/data 

  # 2. Infrastructure: RabbitMQ Message Broker Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: codespace_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672
      - 15672:15672

  # 3. Development Environment: The Workspace Container (Primary Dev Spot)
  workspace:
    # Build the image using our local Dockerfile
    build: 
      context: ./.devcontainer
      dockerfile: devcontainer.Dockerfile
    container_name: codespace_workspace
    volumes:
      # Mount the repository into the workspace container
      - .:/workspaces:cached
      
    # Ensure this container is attached to the same network as Redis/RabbitMQ
    depends_on:
      - redis
      - rabbitmq
    
volumes:
  redis_data:
  rabbitmq_data: