version: '3.8'

services:
  # 1. Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: codespace_redis
    command: redis-server --appendonly yes
    ports:
      - 6379:6379 # Expose Redis port

  # 2. RabbitMQ Message Broker Service (with Admin UI)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: codespace_rabbitmq
    environment:
      # Credentials for connection
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672 # Standard AMQP port for code connection
      - 15672:15672 # Admin UI port (http://localhost:15672)

volumes:
  redis_data:
  rabbitmq_data:
