# docker-compose.yml
version: '3.8'

services:
  # 1. Infrastructure: Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: codespace_redis
    command: redis-server --appendonly yes
    ports: 
      - 6379:6379 
    volumes:
      - redis_data:/data # Persist Redis data

  # 2. Infrastructure: RabbitMQ Message Broker Service
  rabbitmq:
    image: rabbitmq:3-management
    container_name: codespace_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 5672:5672   # AMQP port
      - 15672:15672 # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist RabbitMQ data

  # 3. Development Environment: The Workspace Container (THE FIX)
  workspace:
    # Build the image using the dedicated Dockerfile in the .devcontainer folder
    build: 
      context: ./.devcontainer
      dockerfile: devcontainer.Dockerfile
    container_name: codespace_workspace
    
    # Map the entire repository into the container's workspace folder
    volumes:
      - .:/workspaces:cached
      
    # Keep the container running indefinitely so VS Code can attach to it.
    entrypoint: /bin/sh -c "while sleep 1000; do :; done" 

volumes:
  redis_data:
  rabbitmq_data: